package me.mrletsplay.j4xp.natives.enums;

import me.mrletsplay.j4xp.natives.interfaces.XPWidgetPropertyID;

public enum XPStandardWidgetPropertyID implements XPWidgetPropertyID {
	
	REFCON(0),
	DRAGGING(1),
	DRAG_X_OFF(2),
	DRAG_Y_OFF(3),
	HILITED(4),
	OBJECT(5),
	CLIP(6),
	ENABLED(7),
	
	MAIN_WINDOW_TYPE(1100),
	MAIN_WINDOW_HAS_CLOSE_BOXES(1200),
	
	SUB_WINDOW_TYPE(1200),
	
	BUTTON_TYPE(1300),
	BUTTON_BEHAVIOR(1301),
	BUTTON_STATE(1302),
	
	TEXT_FIELD_EDIT_SEL_START(1400),
	TEXT_FIELD_EDIT_SEL_END(1401),
	TEXT_FIELD_EDIT_SEL_DRAG_START(1402),
	TEXT_FIELD_TYPE(1403),
	TEXT_FIELD_PASSWORD_MODE(1404),
	TEXT_FIELD_MAX_CHARACTERS(1405),
	TEXT_FIELD_SCROLL_POSITION(1406),
	TEXT_FIELD_FONT(1407),
	TEXT_FIELD_ACTIVE_EDIT_SIDE(1408),
	
	SCROLL_BAR_SLIDER_POSITION(1500),
	SCROLL_BAR_MIN(1501),
	SCROLL_BAR_MAX(1502),
	SCROLL_BAR_PAGE_AMOUNT(1503),
	SCROLL_BAR_TYPE(1504),
	SCROLL_BAR_SLOP(1505),
	
	CAPTION_LIT(1600),
	
	GENERAL_GRAPHICS_TYPE(1700),
	
	PROGRESS_POSITION(1800),
	PROGRESS_MIN(1801),
	PROGRESS(1802),
	
	USER_START(10000),
	;

	private int id;
	
	private XPStandardWidgetPropertyID(int id) {
		this.id = id;
	}
	
	@Override
	public int getPropertyID() {
		return id;
	}

}
