package me.mrletsplay.j4xp.natives;

public class XPStandardPropertyValues {

	public static final int
		MAIN_WINDOW_STYLE_MAIN_WINDOW = 0,
		MAIN_WINDOW_STYLE_TRANSLUCENT = 1,
		
		SUB_WINDOW_STYLE_SUB_WINDOW = 0,
		SUB_WINDOW_STYLE_SCREEN = 2,
		SUB_WINDOW_STYLE_LIST_VIEW = 3,
		
		BUTTON_PUSH_BUTTON = 0,
		BUTTON_RADIO_BUTTON = 1,
		BUTTON_WINDOW_CLOSE_BOX = 3,
		BUTTON_LITTLE_DOWN_ARROW = 5,
		BUTTON_LITTLE_UP_ARROW = 6,
		
		BUTTON_BEHAVIOR_PUSH_BUTTON = 0,
		BUTTON_BEHAVIOR_CHECK_BOX = 1,
		BUTTON_BEHAVIOR_RADIO_BUTTON = 2,
		
		TEXT_FIELD_ENTRY_FIELD = 0,
		TEXT_FIELD_TRANSPARENT = 3,
		TEXT_FIELD_TRANSLUCENT = 4,
		
		SCROLL_BAR_TYPE_SCROLL_BAR = 0,
		SCROLL_BAR_TYPE_SLIDER = 1,
		
		GENERAL_GRAPHICS_SHIP = 4,
		GENERAL_GRAPHICS_ILS_GLIDE_SCOPE = 5,
		GENERAL_GRAPHICS_MARKER_LEFT = 6,
		GENERAL_GRAPHICS_AIRPORT = 7,
		GENERAL_GRAPHICS_NDB = 8,
		GENERAL_GRAPHICS_VOR = 9,
		GENERAL_GRAPHICS_RADIO_TOWER = 10,
		GENERAL_GRAPHICS_AIRCRAFT_CARRIER = 11,
		GENERAL_GRAPHICS_FIRE = 12,
		GENERAL_GRAPHICS_MARKER_RIGHT = 13,
		GENERAL_GRAPHICS_CUSTOM_OBJECT = 14,
		GENERAL_GRAPHICS_COOLING_TOWER = 15,
		GENERAL_GRAPHICS_SMOKE_STACK = 16,
		GENERAL_GRAPHICS_BUILDING = 17,
		GENERAL_GRAPHICS_POWER_LINE = 18,
		GENERAL_GRAPHICS_VOR_WITH_COMPASS_ROSE = 19,
		GENERAL_GRAPHICS_OIL_PLATFORM = 21,
		GENERAL_GRAPHICS_OIL_PLATFORM_SMALL = 22,
		GENERAL_GRAPHICS_WAY_POINT = 23
		;
	
}
