/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_mrletsplay_j4xp_natives_XPNativeInterface */

#ifndef _Included_me_mrletsplay_j4xp_natives_XPNativeInterface
#define _Included_me_mrletsplay_j4xp_natives_XPNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_mrletsplay_j4xp_natives_XPNativeInterface
 * Method:    executeFunction
 * Signature: (ILjava/lang/String;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_me_mrletsplay_j4xp_natives_XPNativeInterface_executeFunction
  (JNIEnv *, jclass, jint, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
